version: 2.1
orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    docker: 
      - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
  build-android:
    docker:
      - image: circleci/android:api-25-alpha
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello Android" # run the `echo` command

  build-macos: 
    macos:  
      xcode: 11.3.0
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello macOs" # run the `echo` command

  build-windows:
    executor: win/vs2019
    steps:
      - checkout
      - run: Write-Host 'Hello, Windows'